# Generated by Django 2.1.7 on 2019-03-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ip', models.GenericIPAddressField(verbose_name='内网')),
                ('pub_ip', models.GenericIPAddressField(verbose_name='公网')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('refer', models.URLField(blank=True, null=True, verbose_name='来源')),
                ('timeIn', models.CharField(max_length=16, null=True, verbose_name='进入时间戳')),
                ('time', models.IntegerField(null=True, verbose_name='停留时间')),
                ('timeOut', models.CharField(max_length=16, null=True, verbose_name='离开时间戳')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='浏览器信息')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='ip地区')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
    ]
