# Generated by Django 2.1.7 on 2019-03-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='日期')),
                ('pc_count', models.IntegerField(blank=True, default=0, verbose_name='非移动设备')),
                ('mobile_count', models.IntegerField(blank=True, default=0, verbose_name='移动设备')),
            ],
            options={
                'verbose_name': '每日访问设备统计',
                'verbose_name_plural': '每日访问设备统计',
            },
        ),
        migrations.CreateModel(
            name='ReferByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='日期')),
                ('search_engine_count', models.IntegerField(blank=True, default=0, verbose_name='搜索引擎')),
                ('website_in_count', models.IntegerField(blank=True, default=0, verbose_name='站内')),
                ('other_count', models.IntegerField(blank=True, default=0, verbose_name='其他')),
                ('input_count', models.IntegerField(blank=True, default=0, verbose_name='输入/书签')),
            ],
            options={
                'verbose_name': '每日网站访问来源统计',
                'verbose_name_plural': '每日网站访问来源统计',
            },
        ),
        migrations.CreateModel(
            name='RegionByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=50, verbose_name='地区')),
                ('views_count', models.IntegerField(blank=True, default=0, verbose_name='浏览次数')),
                ('date', models.DateField(auto_now_add=True, verbose_name='日期')),
            ],
            options={
                'verbose_name': '每日地区访问量统计',
                'verbose_name_plural': '每日地区访问量统计',
            },
        ),
        migrations.CreateModel(
            name='ViewsByDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, unique=True, verbose_name='日期')),
                ('views_count', models.IntegerField(blank=True, default=0, verbose_name='浏览次数')),
                ('ip_count', models.IntegerField(blank=True, default=0, verbose_name='ip数')),
            ],
            options={
                'verbose_name': '每天访问量统计',
                'verbose_name_plural': '每天访问量统计',
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_ip', models.GenericIPAddressField(verbose_name='内网')),
                ('pub_ip', models.GenericIPAddressField(db_index=True, verbose_name='公网')),
                ('url', models.URLField(blank=True, null=True, verbose_name='url')),
                ('refer', models.URLField(blank=True, null=True, verbose_name='来源')),
                ('timeIn', models.BigIntegerField(db_index=True, null=True, verbose_name='进入时间戳')),
                ('time', models.IntegerField(null=True, verbose_name='停留时间')),
                ('timeOut', models.BigIntegerField(null=True, verbose_name='离开时间戳')),
                ('user_agent', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='浏览器信息')),
                ('address', models.CharField(blank=True, db_index=True, max_length=500, null=True, verbose_name='ip地区')),
            ],
            options={
                'verbose_name': '访客信息',
                'verbose_name_plural': '访客信息',
            },
        ),
        migrations.AlterUniqueTogether(
            name='regionbyday',
            unique_together={('region', 'date')},
        ),
    ]
