# Generated by Django 2.1.7 on 2019-04-23 14:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128, verbose_name='标题')),
                ('title_en', models.CharField(default='', max_length=128, null=True, verbose_name='标题')),
                ('title_es', models.CharField(default='', max_length=128, null=True, verbose_name='标题')),
                ('title_pt', models.CharField(default='', max_length=128, null=True, verbose_name='标题')),
                ('title_ja', models.CharField(default='', max_length=128, null=True, verbose_name='标题')),
                ('title_ko', models.CharField(default='', max_length=128, null=True, verbose_name='标题')),
                ('image', models.ImageField(max_length=512, upload_to='banner', verbose_name='轮播图')),
                ('url', models.URLField(blank=True, max_length=256, null=True, verbose_name='访问地址')),
                ('index', models.IntegerField(default=0, unique=True, verbose_name='轮播顺序（第一个轮播图必须为0）')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_ja', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_ko', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='商品名', max_length=100, verbose_name='商品名')),
                ('name_en', models.CharField(help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('name_es', models.CharField(help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('name_pt', models.CharField(help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('name_ja', models.CharField(help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('name_ko', models.CharField(help_text='商品名', max_length=100, null=True, verbose_name='商品名')),
                ('goods_sn', models.CharField(max_length=128, unique=True, verbose_name='商品编码')),
                ('goods_front_img', models.ImageField(upload_to='goods/images', verbose_name='商品封面')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('desc_es', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('desc_pt', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('desc_ja', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('desc_ko', models.TextField(blank=True, null=True, verbose_name='商品描述')),
                ('detail', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('detail_en', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('detail_es', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('detail_pt', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('detail_ja', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('detail_ko', mdeditor.fields.MDTextField(blank=True, default='', null=True, verbose_name='商品详情')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('title_es', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('title_pt', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('title_ja', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('title_ko', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('keywords', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('keywords_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('keywords_es', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('keywords_pt', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('keywords_ja', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('keywords_ko', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('description_en', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('description_es', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('description_pt', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('description_ja', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('description_ko', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
                ('leval', models.IntegerField(default=0, verbose_name='权重')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='属性名', max_length=100, verbose_name='属性名')),
                ('name_en', models.CharField(help_text='属性名', max_length=100, null=True, verbose_name='属性名')),
                ('name_es', models.CharField(help_text='属性名', max_length=100, null=True, verbose_name='属性名')),
                ('name_pt', models.CharField(help_text='属性名', max_length=100, null=True, verbose_name='属性名')),
                ('name_ja', models.CharField(help_text='属性名', max_length=100, null=True, verbose_name='属性名')),
                ('name_ko', models.CharField(help_text='属性名', max_length=100, null=True, verbose_name='属性名')),
                ('value', models.CharField(help_text='属性值', max_length=100, verbose_name='属性值')),
                ('value_en', models.CharField(help_text='属性值', max_length=100, null=True, verbose_name='属性值')),
                ('value_es', models.CharField(help_text='属性值', max_length=100, null=True, verbose_name='属性值')),
                ('value_pt', models.CharField(help_text='属性值', max_length=100, null=True, verbose_name='属性值')),
                ('value_ja', models.CharField(help_text='属性值', max_length=100, null=True, verbose_name='属性值')),
                ('value_ko', models.CharField(help_text='属性值', max_length=100, null=True, verbose_name='属性值')),
            ],
            options={
                'verbose_name': '商品属性',
                'verbose_name_plural': '商品属性',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/banner', verbose_name='商品轮播图')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='访问地址')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序（第一个轮播图必须为0）')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_ja', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('alt_ko', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片alt')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('title_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('title_es', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('title_pt', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('title_ja', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('title_ko', models.CharField(blank=True, max_length=100, null=True, verbose_name='图片title')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品轮播图',
                'verbose_name_plural': '商品轮播图',
            },
        ),
        migrations.CreateModel(
            name='GoodsSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='系列名', max_length=50, unique=True, verbose_name='系列名')),
                ('name_en', models.CharField(help_text='系列名', max_length=50, null=True, unique=True, verbose_name='系列名')),
                ('name_es', models.CharField(help_text='系列名', max_length=50, null=True, unique=True, verbose_name='系列名')),
                ('name_pt', models.CharField(help_text='系列名', max_length=50, null=True, unique=True, verbose_name='系列名')),
                ('name_ja', models.CharField(help_text='系列名', max_length=50, null=True, unique=True, verbose_name='系列名')),
                ('name_ko', models.CharField(help_text='系列名', max_length=50, null=True, unique=True, verbose_name='系列名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品系列',
                'verbose_name_plural': '商品系列',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquire', models.CharField(max_length=100, verbose_name='商品型号')),
                ('name', models.CharField(help_text='游客', max_length=100, verbose_name='游客')),
                ('phone', models.CharField(blank=True, help_text='手机号', max_length=15, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='地址')),
                ('message', models.TextField(verbose_name='留言')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='留言时间')),
            ],
            options={
                'verbose_name': '留言板内容',
                'verbose_name_plural': '留言板内容',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='视频标题', max_length=1000, verbose_name='视频标题')),
                ('title_en', models.CharField(help_text='视频标题', max_length=1000, null=True, verbose_name='视频标题')),
                ('title_es', models.CharField(help_text='视频标题', max_length=1000, null=True, verbose_name='视频标题')),
                ('title_pt', models.CharField(help_text='视频标题', max_length=1000, null=True, verbose_name='视频标题')),
                ('title_ja', models.CharField(help_text='视频标题', max_length=1000, null=True, verbose_name='视频标题')),
                ('title_ko', models.CharField(help_text='视频标题', max_length=1000, null=True, verbose_name='视频标题')),
                ('video', models.FileField(upload_to='video/', verbose_name='视频(MP4、FLV)')),
                ('image', models.CharField(blank=True, default='none', max_length=512, null=True, verbose_name='封面(不用手动添加此项)')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '视频',
                'verbose_name_plural': '视频',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='attr',
            field=models.ManyToManyField(related_name='goods', to='goods.GoodsAttributes', verbose_name='商品属性'),
        ),
        migrations.AddField(
            model_name='goods',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsSeries', verbose_name='商品系列'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsimage',
            unique_together={('goods', 'index')},
        ),
    ]
