# Generated by Django 2.1.7 on 2019-03-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='封面'),
        ),
    ]
