# Generated by Django 2.1.7 on 2019-03-28 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscategory',
            name='name',
            field=models.CharField(blank=True, help_text='类别名', max_length=50, unique=True, verbose_name='类别名'),
        ),
        migrations.AlterField(
            model_name='goodsseries',
            name='name',
            field=models.CharField(blank=True, help_text='系列名', max_length=50, unique=True, verbose_name='系列名'),
        ),
    ]
