# Generated by Django 2.1.7 on 2019-03-06 13:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=128, verbose_name='标题')),
                ('image', models.ImageField(blank=True, max_length=512, upload_to='banner', verbose_name='轮播图')),
                ('url', models.URLField(blank=True, max_length=256, verbose_name='访问地址')),
                ('index', models.IntegerField(blank=True, default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='goods/banner', verbose_name='商品轮播图')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='图片url')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
            },
        ),
        migrations.RenameField(
            model_name='goods',
            old_name='img',
            new_name='goods_front_img',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='商品编码'),
        ),
        migrations.AddField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类别'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.TextField(blank=True, verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='detail',
            field=mdeditor.fields.MDTextField(blank=True, default='', verbose_name='商品详情'),
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品轮播图'),
        ),
    ]
