# Generated by Django 2.1.7 on 2019-04-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsattributes',
            name='weight',
            field=models.IntegerField(default=0, help_text='属性权重', verbose_name='属性权重'),
        ),
    ]
