# Generated by Django 2.1.7 on 2019-03-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='alt',
            field=models.CharField(blank=True, max_length=100, verbose_name='图片alt'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='keywords'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='alt',
            field=models.CharField(blank=True, max_length=100, verbose_name='图片alt'),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='图片title'),
        ),
    ]
