# Generated by Django 2.1.7 on 2019-03-30 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190328_2348'),
        ('goods', '0002_auto_20190328_1357'),
    ]

    operations = [
    ]
