# Generated by Django 2.1.7 on 2019-04-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodsattributes_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsimage',
            name='image_url',
        ),
    ]
