# Generated by Django 2.1.7 on 2019-03-28 13:11

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIntroduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='公司名称')),
                ('detail', mdeditor.fields.MDTextField(verbose_name='详细信息')),
                ('addr', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='公司地址')),
                ('tel', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='公司电话')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='公司邮箱')),
                ('web', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='公司网站')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='标题', max_length=1000, verbose_name='标题')),
                ('image', models.ImageField(blank=True, upload_to='customer/image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '宣传客户',
                'verbose_name_plural': '宣传客户',
            },
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='厂名', max_length=1000, verbose_name='厂名')),
                ('image', models.ImageField(blank=True, upload_to='factory/image', verbose_name='图片')),
            ],
            options={
                'verbose_name': '工厂信息',
                'verbose_name_plural': '工厂信息',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='title')),
                ('keywords', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='keywords')),
                ('description', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': '首页关键词',
                'verbose_name_plural': '首页关键词',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='新闻标题', max_length=1000, verbose_name='新闻标题')),
                ('image', models.ImageField(upload_to='news/image', verbose_name='封面图片')),
                ('detail', mdeditor.fields.MDTextField(blank=True, verbose_name='新闻详情')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
        migrations.CreateModel(
            name='UserContactInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=100, verbose_name='邮箱')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='国家')),
                ('message', models.TextField(blank=True, default='', verbose_name='联系内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='联系时间')),
            ],
            options={
                'verbose_name': '联系我们',
                'verbose_name_plural': '联系我们',
            },
        ),
    ]
