# Generated by Django 2.1.7 on 2019-03-13 23:16

import datetime
from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='新闻标题', max_length=1000, verbose_name='新闻标题')),
                ('detail', mdeditor.fields.MDTextField(blank=True, verbose_name='新闻详情')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='发布时间')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
            },
        ),
    ]
