# Generated by Django 2.1.7 on 2019-04-24 12:20

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info',
            field=mdeditor.fields.MDTextField(default='', verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info_en',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info_es',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info_ja',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info_ko',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='customer_info_pt',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='顾客页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info',
            field=mdeditor.fields.MDTextField(default='', verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info_en',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info_es',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info_ja',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info_ko',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='factory_info_pt',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='工厂页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info',
            field=mdeditor.fields.MDTextField(default='', verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info_en',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info_es',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info_ja',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info_ko',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='news_info_pt',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='新闻页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info',
            field=mdeditor.fields.MDTextField(default='', verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info_en',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info_es',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info_ja',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info_ko',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='product_info_pt',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='产品页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info',
            field=mdeditor.fields.MDTextField(default='', verbose_name='视频页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info_en',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='视频页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info_es',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='视频页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info_ja',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='视频页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info_ko',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='视频页描述'),
        ),
        migrations.AlterField(
            model_name='pageinformation',
            name='video_info_pt',
            field=mdeditor.fields.MDTextField(default='', null=True, verbose_name='视频页描述'),
        ),
    ]
